language: python

sudo: false

matrix:
    include:
        - &pylint
          env: RUN_PYLINT=true
          python: '3.4'
          addons: { apt: { packages: [] } }
          cache: {}
        - python: '3.4'
        - python: '3.5'
        - &docs
          env: BUILD_DOCS=true
          python: '3.4'
          script: source $TRAVIS_BUILD_DIR/.travis/build_doc.sh
        - python: '3.5'
          env: PYQT5=true
          dist: trusty
          addons: { apt: { packages: [] } }
    allow_failures:
        - *pylint
    fast_finish: true

cache:
    apt: true
    pip: true
    ccache: true
    directories:
        - $TRAVIS_BUILD_DIR/postgres
        - $TRAVIS_BUILD_DIR/pyqt

before_cache:

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - libqt4-dev
            - gfortran

before_install:
    - set -e  # fail on any error
    - source $TRAVIS_BUILD_DIR/.travis/util.sh

install:
    - source $TRAVIS_BUILD_DIR/.travis/stage_install.sh

script:
    - source $TRAVIS_BUILD_DIR/.travis/stage_script.sh

after_success:
    - source $TRAVIS_BUILD_DIR/.travis/stage_after_success.sh
