language: python

sudo: false
dist: trusty

matrix:
    include:
        - env: RUN_PYLINT=true
          python: '3.6'
          cache: {}
        - env: BUILD_DOCS=true
          python: '3.6'
          script: source $TRAVIS_BUILD_DIR/.travis/build_doc.sh
        - python: '3.5'
          env: PYQT4=true
        - python: '3.6'
          env: UPLOAD_COVERAGE=true
    fast_finish: true

cache:
    apt: true
    pip: true
    ccache: true
    directories:
        - $TRAVIS_BUILD_DIR/postgres
        - $TRAVIS_BUILD_DIR/pyqt

before_cache:

before_install:
    - set -e  # fail on any error
    - source $TRAVIS_BUILD_DIR/.travis/util.sh

install:
    - source $TRAVIS_BUILD_DIR/.travis/stage_install.sh

script:
    - source $TRAVIS_BUILD_DIR/.travis/stage_script.sh

after_success:
    - source $TRAVIS_BUILD_DIR/.travis/stage_after_success.sh
