language: python

sudo: false
dist: trusty

python:
    - '3.4'
    - '3.5'
    - 'nightly'

cache:
    apt: true
    directories:
        - $TRAVIS_BUILD_DIR/postgres
        - $TRAVIS_BUILD_DIR/pyqt
        - $HOME/.cache/pip
        - $HOME/.ccache

before_cache:

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - postgresql-server-dev-9.1
            - libqt4-dev
            - gfortran

before_install:
    - set -e  # fail on any error
    - pip install codecov
    - if [ $TRAVIS_REPO_SLUG = biolab/orange3 ]; then
        source $TRAVIS_BUILD_DIR/.travis/decrypt_upload_doc_id.sh;
      fi

install:
    - source $TRAVIS_BUILD_DIR/.travis/install.sh
    - source $TRAVIS_BUILD_DIR/.travis/install_postgres.sh
    - source $TRAVIS_BUILD_DIR/.travis/install_pyqt.sh
    - source $TRAVIS_BUILD_DIR/.travis/build_doc.sh

before_script:
    - pip install coveralls

script:
    - cd $TRAVIS_BUILD_DIR/dist/Orange-*
    - python -c "from Orange.tests import *"
    - PYTHONUNBUFFERED=x coverage run --source=Orange setup.py test

after_success:
    - cd $TRAVIS_BUILD_DIR
    - codecov
    - if [ $TRAVIS_REPO_SLUG = biolab/orange3 ] && [ $TRAVIS_PULL_REQUEST = false ]; then
        source $TRAVIS_BUILD_DIR/.travis/upload_doc.sh;
      fi
